version: '3.0'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${ELDERY_GROCERY_DELIVERY_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${ELDERY_GROCERY_DELIVERY_DATABASE_PASSWORD}

    volumes:
      - ./tmp/db:/var/lib/postgresql/data  

  webpacker:
    image: ${DOCKER_IMAGE_NAME-elderly}
    command: bash -c "export NODE_OPTIONS="--max_old_space_size=4096" && yarn && rm -rf /opt/elderly/public/packs && bin/webpack-dev-server"
    volumes:
      - .:/opt/elderly
    ports:
      - 3035:3035

  web:
    image: ${DOCKER_IMAGE_NAME-elderly}
    build:
      context: .
      args:
        precompileassets: 'not'
    depends_on:
      - db
      - webpacker
    ports:
      - 80:3000
    command: bash -c "rm -f tmp/pids/server.pid && /usr/wait-for-it.sh --timeout=0 db:5432  && rails db:create && rails db:migrate && rails s -b '0.0.0.0'"
    volumes:
      - .:/opt/elderly
